version: '3'
services:
  react-app:
    build: ./client/c-w-app
    image: react-app
    stdin_open: true
    volumes:
      - ./client/c-w-app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build: ./
    image: api-server
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge

